// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: tempController_2_gui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_tempLabel;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_wifiStatusLabel;
lv_obj_t * ui_ventStatusLabel;
lv_obj_t * ui_shadeStatusLabel;
lv_obj_t * ui_heaterStatusLabel;
lv_obj_t * ui_wifiStatusLabel1;
lv_obj_t * ui_ventStatusLabel1;
lv_obj_t * ui_heaterStatusLabel1;
lv_obj_t * ui_shadeStatusLabel1;
lv_obj_t * ui_otherLabel1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_otherLabel;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_vent25;
lv_obj_t * ui_vent50;
lv_obj_t * ui_vent100;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_heatNight;
lv_obj_t * ui_heatDay;
lv_obj_t * ui_startDay;
lv_obj_t * ui_Label12;
lv_obj_t * ui_startNight;
lv_obj_t * ui_startShade;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_endShade;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_boostStart;
lv_obj_t * ui_boostTemp;
lv_obj_t * ui_boostDur;
lv_obj_t * ui_tempChart;
lv_obj_t * ui_date;
lv_obj_t * ui_time;
lv_obj_t * ui_Relay_States;
lv_obj_t * ui_boostStatusLabel;
lv_obj_t * ui_boxVentOpenIndicator;
lv_obj_t * ui_boxVentCloseIndicator;
lv_obj_t * ui_boxHeaterIndicator;
lv_obj_t * ui_boxShadeCloseIndicator;
lv_obj_t * ui_boxShadeOpenIndicator;
lv_obj_t * ui_Relay_States1;
lv_obj_t * ui_Relay_States2;
lv_obj_t * ui_Relay_States3;
lv_obj_t * ui_Relay_States4;
lv_obj_t * ui_Relay_States5;
lv_obj_t * ui_Relay_States6;
lv_obj_t * ui_Relay_States7;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
