// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: tempController_2_gui

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 351);
    lv_obj_set_height(ui_Panel1, 238);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -273);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Image1, &ui_img_cgflogo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -300);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -43);
    lv_obj_set_y(ui_Label2, -196);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Current Temp:");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, 109);
    lv_obj_set_y(ui_tempLabel, -196);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "25.0");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0xEC0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempChart = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_tempChart, 383);
    lv_obj_set_height(ui_tempChart, 123);
    lv_obj_set_x(ui_tempChart, 0);
    lv_obj_set_y(ui_tempChart, 281);
    lv_obj_set_align(ui_tempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_tempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_tempChart, 100);
    lv_chart_set_range(ui_tempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 35);
    lv_chart_set_div_line_count(ui_tempChart, 10, 5);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);

    ui_date = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 0);
    lv_obj_set_y(ui_date, -90);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "May 12, 2025");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -129);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "18:45:00");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, 0);
    lv_obj_set_y(ui_statusLabel, -51);
    lv_obj_set_align(ui_statusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLabel, "status	");
    lv_obj_set_style_text_font(ui_statusLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatusLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_wifiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStatusLabel, 0);
    lv_obj_set_y(ui_wifiStatusLabel, -11);
    lv_obj_set_align(ui_wifiStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStatusLabel, "status	");
    lv_obj_set_style_text_font(ui_wifiStatusLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

}
